### PR TITLE
iOS part

### PR DESCRIPTION
**Pull request by zaubererty**
I needed the iOS part of this, so I implemented this side.

File and Text is testet, I assume the image is working as well.

As I'm not an ObjC expert this is might a bad  example, but it's working.

### CODE REVIEW

**Comment by nsharma098** [comment]
@zaubererty  and @PieterAelse  can you please show how to receive data string in ios device.

**Comment by gcstr** [comment]
Hello, @zaubererty. Did you tested it against v1.0?
I couldn’t make it work so far.

**Comment by PieterAelse** [comment]
@nsharma098 I basically just use the full image path to share the image. This code works on both Android and iOS (for my case):
`await Share.image(path: imagePath, title: imageName).share();`

**Comment by zaubererty** [comment]
@gcstr had my app running at the last beta an curretntly in the middle of upgrading it.

**Comment by jonnytest1** [comment]
can you double check if integration with package support is possible for iOS (im not very familiar with the syntax ) similar to this : https://github.com/d-silveira/flutter-share/pull/15

**Comment by MperorM** [comment]
@zaubererty

For the android version I needed to update my MainActivity.kt to avoid:
```
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/receiveshare)
```

Is there some way which I should be changing the AppDelegate.swift as well for it to work on IOS to avoid this error? If not, do you know what else could be causing it to occur on IOS?

**Pull request merged**
